apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: muddledluck170/auth
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_KEY
            - name: JWT_ACCESS_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_ACCESS_TOKEN_TTL
            - name: JWT_REFRESH_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_REFRESH_TOKEN_TTL
            - name: JWT_FORGET_PASSWORD_TOKEN_TTL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: JWT_FORGET_PASSWORD_TOKEN_TTL
            - name: DB_HOST
              value: "auth-postgres-srv"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 4000
      targetPort: 4000
