apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-postgres
  template:
    metadata:
      labels:
        app: post-postgres
    spec:
      containers:
        - name: post-postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: post-postgres-srv
spec:
  selector:
    app: post-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
